apiVersion: v1
kind: Config
clusters:
- cluster:
server: https://192.168.0.20:8443
certificate-authority: /root/ca.crt
name: minikube
contexts:
- context:
cluster: minikube
user: ravi
users:
- name: ravi
user:
client-key: /root/client.key
client-certificate: /root/client.crt